ALTER TABLE financing
   DROP CONSTRAINT FK_FINANCIN_FINANCING_COMPETIT;

ALTER TABLE financing
   DROP CONSTRAINT FK_FINANCIN_FINANCING_FUNDING;

ALTER TABLE footballer
   DROP CONSTRAINT FK_FOOTBALL_CONN_TEAM_TEAM;

ALTER TABLE judging
   DROP CONSTRAINT FK_JUDGING_JUDGING_COMPETIT;

ALTER TABLE judging
   DROP CONSTRAINT FK_JUDGING_JUDGING2_JUDGE;

ALTER TABLE org_compet
   DROP CONSTRAINT FK_ORG_COMP_ORG_COMPE_ORGANIZE;

ALTER TABLE org_compet
   DROP CONSTRAINT FK_ORG_COMP_ORG_COMPE_COMPETIT;

ALTER TABLE participation
   DROP CONSTRAINT FK_PARTICIP_PARTICIPA_TEAM;

ALTER TABLE participation
   DROP CONSTRAINT FK_PARTICIP_PARTICIPA_COMPETIT;

ALTER TABLE partip_rating
   DROP CONSTRAINT FK_PARTIP_R_PARTIP_RA_PLACE_IN;

ALTER TABLE partip_rating
   DROP CONSTRAINT FK_PARTIP_R_PARTIP_RA_TEAM;

ALTER TABLE place_int_rating
   DROP CONSTRAINT FK_PLACE_IN_PART_BY_V_VERSION_;

ALTER TABLE team_c
   DROP CONSTRAINT FK_TEAM_C_TEAM_C_V_TEAM;

ALTER TABLE team_club
   DROP CONSTRAINT FK_TEAM_CLU_TEAM_CL_TEAM;